name: Sync repo to GCS

on:
  push:
    branches: [ main ]
    paths:
      - 'dags/**'
      - 'plugins/**'
      - 'dbt/**'
      - 'plug/**'
      - 'logs/**'


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v3'
        with:
          project_id: 'airflow-soln-project'
          workload_identity_provider: 'projects/70063168308/locations/global/workloadIdentityPools/oltp-olap-main-pool/providers/oltp-olap-main-pool-provider'


      - name: Sync DAGs to GCS
        run: |
          [ -d "./dags" ] && gsutil -m rsync -r ./dags gs://prod_oltp_to_olap_test/dags
          [ -d "./plugins" ] && gsutil -m rsync -r ./plugins gs://prod_oltp_to_olap_test/plugins
          [ -d "./dbt" ] && gsutil -m rsync -r ./dbt gs://prod_oltp_to_olap_test/dbt
          [ -d "./plugs" ] && gsutil -m rsync -r ./plugs gs://prod_oltp_to_olap_test/plugs